name: Update What's New
on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"  # daily ~10:00 AM America/Chicago
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil
      - run: python .github/scripts/update_whats_new.py
      - run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/whats-new.md
            git commit -m "chore: update whats-new.md"
            git push
          fi
